# Generated by Django 4.1 on 2022-08-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0002_alter_project_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project", name="icon", field=models.CharField(max_length=30),
        ),
    ]
