# Generated by Django 4.1 on 2022-08-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0005_experience_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience", name="end_date", field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="experience", name="start_date", field=models.DateField(),
        ),
    ]
