# Generated by Django 4.1 on 2022-08-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0006_alter_experience_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
